import 'package:auto_route/auto_route.dart';
import 'package:blogs/core/constant/my_assets.dart';
import 'package:blogs/presentation/routes/router_imports.gr.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:velocity_x/velocity_x.dart';
import '../../common_widgets/common_widgets_import.dart';
part 'auth_view_model.dart';
part 'auth.dart';